# Generated by Django 5.0.6 on 2024-05-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("photo", models.ImageField(upload_to="animals_image")),
                (
                    "sex",
                    models.TextField(
                        choices=[("male", "Male"), ("female", "Female")], default="male"
                    ),
                ),
                ("age", models.IntegerField()),
                ("description", models.TextField()),
                ("countOfFavor", models.IntegerField()),
                ("specifics", models.CharField(max_length=255)),
                ("history", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("photo", models.ImageField(upload_to="animals_image")),
                (
                    "sex",
                    models.TextField(
                        choices=[("male", "Male"), ("female", "Female")], default="male"
                    ),
                ),
                ("age", models.IntegerField()),
                ("description", models.TextField()),
                ("countOfFavor", models.IntegerField()),
                ("specifics", models.CharField(max_length=255)),
                ("history", models.TextField()),
                (
                    "size",
                    models.CharField(
                        choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                        default="S",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
