# Generated by Django 5.0.6 on 2024-06-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usolapohvist_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="character",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dog",
            name="character",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
