# Generated by Django 5.0.6 on 2024-06-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usolapohvist_app", "0002_cat_character_dog_character"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat",
            name="photo",
            field=models.ImageField(
                upload_to="animals_image/usolapohvist_app.models/% Y/% m/%"
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="photo",
            field=models.ImageField(
                upload_to="animals_image/usolapohvist_app.models/% Y/% m/%"
            ),
        ),
    ]
