# Generated by Django 5.0.6 on 2024-06-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usolapohvist_app", "0003_alter_cat_photo_alter_dog_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagesForAnimals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to='"animals_image/%Y/%m/%d/"')),
            ],
        ),
        migrations.AlterField(
            model_name="cat",
            name="countOfFavor",
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="cat",
            name="photo",
        ),
        migrations.AlterField(
            model_name="dog",
            name="countOfFavor",
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="dog",
            name="photo",
        ),
        migrations.AddField(
            model_name="cat",
            name="photo",
            field=models.ManyToManyField(
                related_name="cat_photo", to="usolapohvist_app.imagesforanimals"
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="photo",
            field=models.ManyToManyField(
                related_name="dog_photo", to="usolapohvist_app.imagesforanimals"
            ),
        ),
    ]
