# Generated by Django 5.0.6 on 2024-06-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usolapohvist_app", "0004_imagesforanimals_alter_cat_countoffavor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="sterilization",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dog",
            name="sterilization",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="imagesforanimals",
            name="image",
            field=models.ImageField(upload_to="animals_image/%Y/%m/%d/"),
        ),
    ]
