# Generated by Django 5.0.6 on 2024-06-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usolapohvist_app", "0006_cat_vaccination_dog_vaccination"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cat",
            old_name="sterilization",
            new_name="sterilized",
        ),
        migrations.RenameField(
            model_name="cat",
            old_name="vaccination",
            new_name="vaccinated",
        ),
        migrations.RenameField(
            model_name="dog",
            old_name="sterilization",
            new_name="sterilized",
        ),
        migrations.RenameField(
            model_name="dog",
            old_name="vaccination",
            new_name="vaccinated",
        ),
    ]
