# Generated by Django 5.0.6 on 2024-06-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usolapohvist_app", "0007_rename_sterilization_cat_sterilized_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="category",
            field=models.CharField(
                choices=[("dog", "Dog"), ("cat", "Cat")], default="cat"
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="category",
            field=models.CharField(
                choices=[("dog", "Dog"), ("cat", "Cat")], default="cat"
            ),
        ),
    ]
