# Generated by Django 5.0.6 on 2024-06-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usolapohvist_app", "0008_cat_category_dog_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="size",
            field=models.CharField(
                choices=[
                    ("Маленький (до 30 см)", "small"),
                    ("Седерній (30-50 см)", "average"),
                    ("Великий (від 50 см)", "big"),
                ],
                default="S",
                max_length=255,
            ),
        ),
    ]
