# Generated by Django 5.0.6 on 2024-07-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usolapohvist_app", "0010_alter_dog_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat",
            name="sex",
            field=models.TextField(
                choices=[("Хлопчик", "Male"), ("Дівчинка", "Female")], default="male"
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="sex",
            field=models.TextField(
                choices=[("Хлопчик", "Male"), ("Дівчинка", "Female")], default="male"
            ),
        ),
    ]
