# Generated by Django 5.0.6 on 2024-07-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usolapohvist_app", "0011_alter_cat_sex_alter_dog_sex"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cat",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="dog",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="cat",
            name="category",
            field=models.CharField(
                choices=[("dogs", "Dog"), ("cats", "Cat")], default="cat"
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="category",
            field=models.CharField(
                choices=[("dogs", "Dog"), ("cats", "Cat")], default="dog"
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="size",
            field=models.CharField(
                choices=[
                    ("Маленький (до 30 см)", "small"),
                    ("Середній (30-50 см)", "average"),
                    ("Великий (від 50 см)", "big"),
                ],
                default="S",
                max_length=255,
            ),
        ),
    ]
