export type Pet = {
  id: string,
  category: string,
  name: string,
  sex: string,
  age: string | number,
  size?: string | undefined,
  character: string,
  description: string,
  history: string,
  specifics: string,
  sterilized: boolean,
  vaccinated: boolean,
  photo: string | string[],
}